let repoArray = [
    {
        "id": 66195249,
        "name": "JavaScript3",
        "full_name": "HackYourFuture/JavaScript3",
        "owner": {
            "login": "HackYourFuture",
            "id": 20858568,
            "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HackYourFuture",
            "html_url": "https://github.com/HackYourFuture",
            "followers_url": "https://api.github.com/users/HackYourFuture/followers",
            "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
            "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
            "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
            "repos_url": "https://api.github.com/users/HackYourFuture/repos",
            "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/HackYourFuture/JavaScript3",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/HackYourFuture/JavaScript3",
        "forks_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/forks",
        "keys_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/teams",
        "hooks_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/hooks",
        "issue_events_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/issues/events{/number}",
        "events_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/events",
        "assignees_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/assignees{/user}",
        "branches_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/branches{/branch}",
        "tags_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/tags",
        "blobs_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/languages",
        "stargazers_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/stargazers",
        "contributors_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/contributors",
        "subscribers_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/subscribers",
        "subscription_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/subscription",
        "commits_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/contents/{+path}",
        "compare_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/merges",
        "archive_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/downloads",
        "issues_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/issues{/number}",
        "pulls_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/labels{/name}",
        "releases_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/releases{/id}",
        "deployments_url": "https://api.github.com/repos/HackYourFuture/JavaScript3/deployments",
        "created_at": "2016-08-21T11:24:56Z",
        "updated_at": "2016-08-22T13:37:36Z",
        "pushed_at": "2016-08-21T13:58:49Z",
        "git_url": "git://github.com/HackYourFuture/JavaScript3.git",
        "ssh_url": "git@github.com:HackYourFuture/JavaScript3.git",
        "clone_url": "https://github.com/HackYourFuture/JavaScript3.git",
        "svn_url": "https://github.com/HackYourFuture/JavaScript3",
        "homepage": null,
        "size": 5,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 3,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 3,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
    {
        "id": 68593779,
        "name": "Project",
        "full_name": "HackYourFuture/Project",
        "owner": {
            "login": "HackYourFuture",
            "id": 20858568,
            "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HackYourFuture",
            "html_url": "https://github.com/HackYourFuture",
            "followers_url": "https://api.github.com/users/HackYourFuture/followers",
            "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
            "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
            "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
            "repos_url": "https://api.github.com/users/HackYourFuture/repos",
            "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/HackYourFuture/Project",
        "description": "Here you can find specifications and deadlines for the project module",
        "fork": false,
        "url": "https://api.github.com/repos/HackYourFuture/Project",
        "forks_url": "https://api.github.com/repos/HackYourFuture/Project/forks",
        "keys_url": "https://api.github.com/repos/HackYourFuture/Project/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/HackYourFuture/Project/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/HackYourFuture/Project/teams",
        "hooks_url": "https://api.github.com/repos/HackYourFuture/Project/hooks",
        "issue_events_url": "https://api.github.com/repos/HackYourFuture/Project/issues/events{/number}",
        "events_url": "https://api.github.com/repos/HackYourFuture/Project/events",
        "assignees_url": "https://api.github.com/repos/HackYourFuture/Project/assignees{/user}",
        "branches_url": "https://api.github.com/repos/HackYourFuture/Project/branches{/branch}",
        "tags_url": "https://api.github.com/repos/HackYourFuture/Project/tags",
        "blobs_url": "https://api.github.com/repos/HackYourFuture/Project/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/HackYourFuture/Project/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/HackYourFuture/Project/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/HackYourFuture/Project/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/HackYourFuture/Project/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/HackYourFuture/Project/languages",
        "stargazers_url": "https://api.github.com/repos/HackYourFuture/Project/stargazers",
        "contributors_url": "https://api.github.com/repos/HackYourFuture/Project/contributors",
        "subscribers_url": "https://api.github.com/repos/HackYourFuture/Project/subscribers",
        "subscription_url": "https://api.github.com/repos/HackYourFuture/Project/subscription",
        "commits_url": "https://api.github.com/repos/HackYourFuture/Project/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/HackYourFuture/Project/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/HackYourFuture/Project/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/HackYourFuture/Project/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/HackYourFuture/Project/contents/{+path}",
        "compare_url": "https://api.github.com/repos/HackYourFuture/Project/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/HackYourFuture/Project/merges",
        "archive_url": "https://api.github.com/repos/HackYourFuture/Project/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/HackYourFuture/Project/downloads",
        "issues_url": "https://api.github.com/repos/HackYourFuture/Project/issues{/number}",
        "pulls_url": "https://api.github.com/repos/HackYourFuture/Project/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/HackYourFuture/Project/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/HackYourFuture/Project/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/HackYourFuture/Project/labels{/name}",
        "releases_url": "https://api.github.com/repos/HackYourFuture/Project/releases{/id}",
        "deployments_url": "https://api.github.com/repos/HackYourFuture/Project/deployments",
        "created_at": "2016-09-19T10:06:53Z",
        "updated_at": "2016-09-19T10:06:53Z",
        "pushed_at": "2017-05-23T10:36:23Z",
        "git_url": "git://github.com/HackYourFuture/Project.git",
        "ssh_url": "git@github.com:HackYourFuture/Project.git",
        "clone_url": "https://github.com/HackYourFuture/Project.git",
        "svn_url": "https://github.com/HackYourFuture/Project",
        "homepage": null,
        "size": 12,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
    {
        "id": 68617514,
        "name": "HTML-CSS",
        "full_name": "HackYourFuture/HTML-CSS",
        "owner": {
            "login": "HackYourFuture",
            "id": 20858568,
            "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HackYourFuture",
            "html_url": "https://github.com/HackYourFuture",
            "followers_url": "https://api.github.com/users/HackYourFuture/followers",
            "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
            "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
            "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
            "repos_url": "https://api.github.com/users/HackYourFuture/repos",
            "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/HackYourFuture/HTML-CSS",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/HackYourFuture/HTML-CSS",
        "forks_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/forks",
        "keys_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/teams",
        "hooks_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/hooks",
        "issue_events_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/issues/events{/number}",
        "events_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/events",
        "assignees_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/assignees{/user}",
        "branches_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/branches{/branch}",
        "tags_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/tags",
        "blobs_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/languages",
        "stargazers_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/stargazers",
        "contributors_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/contributors",
        "subscribers_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/subscribers",
        "subscription_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/subscription",
        "commits_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/contents/{+path}",
        "compare_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/merges",
        "archive_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/downloads",
        "issues_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/issues{/number}",
        "pulls_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/labels{/name}",
        "releases_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/releases{/id}",
        "deployments_url": "https://api.github.com/repos/HackYourFuture/HTML-CSS/deployments",
        "created_at": "2016-09-19T15:09:45Z",
        "updated_at": "2017-09-12T10:44:51Z",
        "pushed_at": "2017-09-19T11:59:33Z",
        "git_url": "git://github.com/HackYourFuture/HTML-CSS.git",
        "ssh_url": "git@github.com:HackYourFuture/HTML-CSS.git",
        "clone_url": "https://github.com/HackYourFuture/HTML-CSS.git",
        "svn_url": "https://github.com/HackYourFuture/HTML-CSS",
        "homepage": null,
        "size": 1403,
        "stargazers_count": 7,
        "watchers_count": 7,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 29,
        "mirror_url": null,
        "open_issues_count": 6,
        "forks": 29,
        "open_issues": 6,
        "watchers": 7,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
    {
        "id": 68906713,
        "name": "Node.js",
        "full_name": "HackYourFuture/Node.js",
        "owner": {
            "login": "HackYourFuture",
            "id": 20858568,
            "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HackYourFuture",
            "html_url": "https://github.com/HackYourFuture",
            "followers_url": "https://api.github.com/users/HackYourFuture/followers",
            "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
            "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
            "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
            "repos_url": "https://api.github.com/users/HackYourFuture/repos",
            "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/HackYourFuture/Node.js",
        "description": "NodeJS 101 course",
        "fork": false,
        "url": "https://api.github.com/repos/HackYourFuture/Node.js",
        "forks_url": "https://api.github.com/repos/HackYourFuture/Node.js/forks",
        "keys_url": "https://api.github.com/repos/HackYourFuture/Node.js/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/HackYourFuture/Node.js/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/HackYourFuture/Node.js/teams",
        "hooks_url": "https://api.github.com/repos/HackYourFuture/Node.js/hooks",
        "issue_events_url": "https://api.github.com/repos/HackYourFuture/Node.js/issues/events{/number}",
        "events_url": "https://api.github.com/repos/HackYourFuture/Node.js/events",
        "assignees_url": "https://api.github.com/repos/HackYourFuture/Node.js/assignees{/user}",
        "branches_url": "https://api.github.com/repos/HackYourFuture/Node.js/branches{/branch}",
        "tags_url": "https://api.github.com/repos/HackYourFuture/Node.js/tags",
        "blobs_url": "https://api.github.com/repos/HackYourFuture/Node.js/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/HackYourFuture/Node.js/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/HackYourFuture/Node.js/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/HackYourFuture/Node.js/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/HackYourFuture/Node.js/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/HackYourFuture/Node.js/languages",
        "stargazers_url": "https://api.github.com/repos/HackYourFuture/Node.js/stargazers",
        "contributors_url": "https://api.github.com/repos/HackYourFuture/Node.js/contributors",
        "subscribers_url": "https://api.github.com/repos/HackYourFuture/Node.js/subscribers",
        "subscription_url": "https://api.github.com/repos/HackYourFuture/Node.js/subscription",
        "commits_url": "https://api.github.com/repos/HackYourFuture/Node.js/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/HackYourFuture/Node.js/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/HackYourFuture/Node.js/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/HackYourFuture/Node.js/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/HackYourFuture/Node.js/contents/{+path}",
        "compare_url": "https://api.github.com/repos/HackYourFuture/Node.js/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/HackYourFuture/Node.js/merges",
        "archive_url": "https://api.github.com/repos/HackYourFuture/Node.js/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/HackYourFuture/Node.js/downloads",
        "issues_url": "https://api.github.com/repos/HackYourFuture/Node.js/issues{/number}",
        "pulls_url": "https://api.github.com/repos/HackYourFuture/Node.js/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/HackYourFuture/Node.js/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/HackYourFuture/Node.js/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/HackYourFuture/Node.js/labels{/name}",
        "releases_url": "https://api.github.com/repos/HackYourFuture/Node.js/releases{/id}",
        "deployments_url": "https://api.github.com/repos/HackYourFuture/Node.js/deployments",
        "created_at": "2016-09-22T09:36:44Z",
        "updated_at": "2017-09-10T13:22:50Z",
        "pushed_at": "2017-09-16T22:48:59Z",
        "git_url": "git://github.com/HackYourFuture/Node.js.git",
        "ssh_url": "git@github.com:HackYourFuture/Node.js.git",
        "clone_url": "https://github.com/HackYourFuture/Node.js.git",
        "svn_url": "https://github.com/HackYourFuture/Node.js",
        "homepage": null,
        "size": 593,
        "stargazers_count": 8,
        "watchers_count": 8,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 38,
        "mirror_url": null,
        "open_issues_count": 5,
        "forks": 38,
        "open_issues": 5,
        "watchers": 8,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
    {
        "id": 69110046,
        "name": "Databases",
        "full_name": "HackYourFuture/databases",
        "owner": {
            "login": "HackYourFuture",
            "id": 20858568,
            "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HackYourFuture",
            "html_url": "https://github.com/HackYourFuture",
            "followers_url": "https://api.github.com/users/HackYourFuture/followers",
            "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
            "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
            "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
            "repos_url": "https://api.github.com/users/HackYourFuture/repos",
            "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/HackYourFuture/databases",
        "description": "Course notes and examples in MySQL and Mongo from database systems class",
        "fork": false,
        "url": "https://api.github.com/repos/HackYourFuture/databases",
        "forks_url": "https://api.github.com/repos/HackYourFuture/databases/forks",
        "keys_url": "https://api.github.com/repos/HackYourFuture/databases/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/HackYourFuture/databases/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/HackYourFuture/databases/teams",
        "hooks_url": "https://api.github.com/repos/HackYourFuture/databases/hooks",
        "issue_events_url": "https://api.github.com/repos/HackYourFuture/databases/issues/events{/number}",
        "events_url": "https://api.github.com/repos/HackYourFuture/databases/events",
        "assignees_url": "https://api.github.com/repos/HackYourFuture/databases/assignees{/user}",
        "branches_url": "https://api.github.com/repos/HackYourFuture/databases/branches{/branch}",
        "tags_url": "https://api.github.com/repos/HackYourFuture/databases/tags",
        "blobs_url": "https://api.github.com/repos/HackYourFuture/databases/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/HackYourFuture/databases/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/HackYourFuture/databases/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/HackYourFuture/databases/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/HackYourFuture/databases/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/HackYourFuture/databases/languages",
        "stargazers_url": "https://api.github.com/repos/HackYourFuture/databases/stargazers",
        "contributors_url": "https://api.github.com/repos/HackYourFuture/databases/contributors",
        "subscribers_url": "https://api.github.com/repos/HackYourFuture/databases/subscribers",
        "subscription_url": "https://api.github.com/repos/HackYourFuture/databases/subscription",
        "commits_url": "https://api.github.com/repos/HackYourFuture/databases/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/HackYourFuture/databases/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/HackYourFuture/databases/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/HackYourFuture/databases/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/HackYourFuture/databases/contents/{+path}",
        "compare_url": "https://api.github.com/repos/HackYourFuture/databases/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/HackYourFuture/databases/merges",
        "archive_url": "https://api.github.com/repos/HackYourFuture/databases/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/HackYourFuture/databases/downloads",
        "issues_url": "https://api.github.com/repos/HackYourFuture/databases/issues{/number}",
        "pulls_url": "https://api.github.com/repos/HackYourFuture/databases/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/HackYourFuture/databases/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/HackYourFuture/databases/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/HackYourFuture/databases/labels{/name}",
        "releases_url": "https://api.github.com/repos/HackYourFuture/databases/releases{/id}",
        "deployments_url": "https://api.github.com/repos/HackYourFuture/databases/deployments",
        "created_at": "2016-09-24T15:21:14Z",
        "updated_at": "2017-09-11T12:07:14Z",
        "pushed_at": "2017-09-16T16:56:55Z",
        "git_url": "git://github.com/HackYourFuture/databases.git",
        "ssh_url": "git@github.com:HackYourFuture/databases.git",
        "clone_url": "https://github.com/HackYourFuture/databases.git",
        "svn_url": "https://github.com/HackYourFuture/databases",
        "homepage": null,
        "size": 1206,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 22,
        "mirror_url": null,
        "open_issues_count": 3,
        "forks": 22,
        "open_issues": 3,
        "watchers": 3,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
    {
        "id": 70716559,
        "name": "JavaScript",
        "full_name": "HackYourFuture/JavaScript",
        "owner": {
            "login": "HackYourFuture",
            "id": 20858568,
            "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HackYourFuture",
            "html_url": "https://github.com/HackYourFuture",
            "followers_url": "https://api.github.com/users/HackYourFuture/followers",
            "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
            "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
            "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
            "repos_url": "https://api.github.com/users/HackYourFuture/repos",
            "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/HackYourFuture/JavaScript",
        "description": "JavaScript modules",
        "fork": false,
        "url": "https://api.github.com/repos/HackYourFuture/JavaScript",
        "forks_url": "https://api.github.com/repos/HackYourFuture/JavaScript/forks",
        "keys_url": "https://api.github.com/repos/HackYourFuture/JavaScript/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/HackYourFuture/JavaScript/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/HackYourFuture/JavaScript/teams",
        "hooks_url": "https://api.github.com/repos/HackYourFuture/JavaScript/hooks",
        "issue_events_url": "https://api.github.com/repos/HackYourFuture/JavaScript/issues/events{/number}",
        "events_url": "https://api.github.com/repos/HackYourFuture/JavaScript/events",
        "assignees_url": "https://api.github.com/repos/HackYourFuture/JavaScript/assignees{/user}",
        "branches_url": "https://api.github.com/repos/HackYourFuture/JavaScript/branches{/branch}",
        "tags_url": "https://api.github.com/repos/HackYourFuture/JavaScript/tags",
        "blobs_url": "https://api.github.com/repos/HackYourFuture/JavaScript/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/HackYourFuture/JavaScript/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/HackYourFuture/JavaScript/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/HackYourFuture/JavaScript/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/HackYourFuture/JavaScript/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/HackYourFuture/JavaScript/languages",
        "stargazers_url": "https://api.github.com/repos/HackYourFuture/JavaScript/stargazers",
        "contributors_url": "https://api.github.com/repos/HackYourFuture/JavaScript/contributors",
        "subscribers_url": "https://api.github.com/repos/HackYourFuture/JavaScript/subscribers",
        "subscription_url": "https://api.github.com/repos/HackYourFuture/JavaScript/subscription",
        "commits_url": "https://api.github.com/repos/HackYourFuture/JavaScript/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/HackYourFuture/JavaScript/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/HackYourFuture/JavaScript/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/HackYourFuture/JavaScript/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/HackYourFuture/JavaScript/contents/{+path}",
        "compare_url": "https://api.github.com/repos/HackYourFuture/JavaScript/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/HackYourFuture/JavaScript/merges",
        "archive_url": "https://api.github.com/repos/HackYourFuture/JavaScript/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/HackYourFuture/JavaScript/downloads",
        "issues_url": "https://api.github.com/repos/HackYourFuture/JavaScript/issues{/number}",
        "pulls_url": "https://api.github.com/repos/HackYourFuture/JavaScript/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/HackYourFuture/JavaScript/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/HackYourFuture/JavaScript/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/HackYourFuture/JavaScript/labels{/name}",
        "releases_url": "https://api.github.com/repos/HackYourFuture/JavaScript/releases{/id}",
        "deployments_url": "https://api.github.com/repos/HackYourFuture/JavaScript/deployments",
        "created_at": "2016-10-12T15:59:04Z",
        "updated_at": "2017-09-19T14:41:08Z",
        "pushed_at": "2017-09-19T14:41:09Z",
        "git_url": "git://github.com/HackYourFuture/JavaScript.git",
        "ssh_url": "git@github.com:HackYourFuture/JavaScript.git",
        "clone_url": "https://github.com/HackYourFuture/JavaScript.git",
        "svn_url": "https://github.com/HackYourFuture/JavaScript",
        "homepage": "",
        "size": 9908,
        "stargazers_count": 20,
        "watchers_count": 20,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 27,
        "mirror_url": null,
        "open_issues_count": 4,
        "forks": 27,
        "open_issues": 4,
        "watchers": 20,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
    {
        "id": 74854737,
        "name": "Git",
        "full_name": "HackYourFuture/Git",
        "owner": {
            "login": "HackYourFuture",
            "id": 20858568,
            "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HackYourFuture",
            "html_url": "https://github.com/HackYourFuture",
            "followers_url": "https://api.github.com/users/HackYourFuture/followers",
            "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
            "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
            "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
            "repos_url": "https://api.github.com/users/HackYourFuture/repos",
            "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/HackYourFuture/Git",
        "description": "This repository contains the course material for the Git course",
        "fork": false,
        "url": "https://api.github.com/repos/HackYourFuture/Git",
        "forks_url": "https://api.github.com/repos/HackYourFuture/Git/forks",
        "keys_url": "https://api.github.com/repos/HackYourFuture/Git/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/HackYourFuture/Git/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/HackYourFuture/Git/teams",
        "hooks_url": "https://api.github.com/repos/HackYourFuture/Git/hooks",
        "issue_events_url": "https://api.github.com/repos/HackYourFuture/Git/issues/events{/number}",
        "events_url": "https://api.github.com/repos/HackYourFuture/Git/events",
        "assignees_url": "https://api.github.com/repos/HackYourFuture/Git/assignees{/user}",
        "branches_url": "https://api.github.com/repos/HackYourFuture/Git/branches{/branch}",
        "tags_url": "https://api.github.com/repos/HackYourFuture/Git/tags",
        "blobs_url": "https://api.github.com/repos/HackYourFuture/Git/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/HackYourFuture/Git/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/HackYourFuture/Git/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/HackYourFuture/Git/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/HackYourFuture/Git/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/HackYourFuture/Git/languages",
        "stargazers_url": "https://api.github.com/repos/HackYourFuture/Git/stargazers",
        "contributors_url": "https://api.github.com/repos/HackYourFuture/Git/contributors",
        "subscribers_url": "https://api.github.com/repos/HackYourFuture/Git/subscribers",
        "subscription_url": "https://api.github.com/repos/HackYourFuture/Git/subscription",
        "commits_url": "https://api.github.com/repos/HackYourFuture/Git/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/HackYourFuture/Git/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/HackYourFuture/Git/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/HackYourFuture/Git/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/HackYourFuture/Git/contents/{+path}",
        "compare_url": "https://api.github.com/repos/HackYourFuture/Git/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/HackYourFuture/Git/merges",
        "archive_url": "https://api.github.com/repos/HackYourFuture/Git/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/HackYourFuture/Git/downloads",
        "issues_url": "https://api.github.com/repos/HackYourFuture/Git/issues{/number}",
        "pulls_url": "https://api.github.com/repos/HackYourFuture/Git/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/HackYourFuture/Git/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/HackYourFuture/Git/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/HackYourFuture/Git/labels{/name}",
        "releases_url": "https://api.github.com/repos/HackYourFuture/Git/releases{/id}",
        "deployments_url": "https://api.github.com/repos/HackYourFuture/Git/deployments",
        "created_at": "2016-11-26T22:45:13Z",
        "updated_at": "2017-07-22T01:41:53Z",
        "pushed_at": "2017-05-23T12:54:22Z",
        "git_url": "git://github.com/HackYourFuture/Git.git",
        "ssh_url": "git@github.com:HackYourFuture/Git.git",
        "clone_url": "https://github.com/HackYourFuture/Git.git",
        "svn_url": "https://github.com/HackYourFuture/Git",
        "homepage": null,
        "size": 18,
        "stargazers_count": 2,
        "watchers_count": 2,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 6,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 6,
        "open_issues": 0,
        "watchers": 2,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
    {
        "id": 75539321,
        "name": "CommandLine",
        "full_name": "HackYourFuture/CommandLine",
        "owner": {
            "login": "HackYourFuture",
            "id": 20858568,
            "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/HackYourFuture",
            "html_url": "https://github.com/HackYourFuture",
            "followers_url": "https://api.github.com/users/HackYourFuture/followers",
            "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
            "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
            "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
            "repos_url": "https://api.github.com/users/HackYourFuture/repos",
            "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
            "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/HackYourFuture/CommandLine",
        "description": "This repository contains the teaching material and notes for the UNIX-based (bash) command line.",
        "fork": false,
        "url": "https://api.github.com/repos/HackYourFuture/CommandLine",
        "forks_url": "https://api.github.com/repos/HackYourFuture/CommandLine/forks",
        "keys_url": "https://api.github.com/repos/HackYourFuture/CommandLine/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/HackYourFuture/CommandLine/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/HackYourFuture/CommandLine/teams",
        "hooks_url": "https://api.github.com/repos/HackYourFuture/CommandLine/hooks",
        "issue_events_url": "https://api.github.com/repos/HackYourFuture/CommandLine/issues/events{/number}",
        "events_url": "https://api.github.com/repos/HackYourFuture/CommandLine/events",
        "assignees_url": "https://api.github.com/repos/HackYourFuture/CommandLine/assignees{/user}",
        "branches_url": "https://api.github.com/repos/HackYourFuture/CommandLine/branches{/branch}",
        "tags_url": "https://api.github.com/repos/HackYourFuture/CommandLine/tags",
        "blobs_url": "https://api.github.com/repos/HackYourFuture/CommandLine/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/HackYourFuture/CommandLine/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/HackYourFuture/CommandLine/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/HackYourFuture/CommandLine/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/HackYourFuture/CommandLine/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/HackYourFuture/CommandLine/languages",
        "stargazers_url": "https://api.github.com/repos/HackYourFuture/CommandLine/stargazers",
        "contributors_url": "https://api.github.com/repos/HackYourFuture/CommandLine/contributors",
        "subscribers_url": "https://api.github.com/repos/HackYourFuture/CommandLine/subscribers",
        "subscription_url": "https://api.github.com/repos/HackYourFuture/CommandLine/subscription",
        "commits_url": "https://api.github.com/repos/HackYourFuture/CommandLine/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/HackYourFuture/CommandLine/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/HackYourFuture/CommandLine/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/HackYourFuture/CommandLine/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/HackYourFuture/CommandLine/contents/{+path}",
        "compare_url": "https://api.github.com/repos/HackYourFuture/CommandLine/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/HackYourFuture/CommandLine/merges",
        "archive_url": "https://api.github.com/repos/HackYourFuture/CommandLine/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/HackYourFuture/CommandLine/downloads",
        "issues_url": "https://api.github.com/repos/HackYourFuture/CommandLine/issues{/number}",
        "pulls_url": "https://api.github.com/repos/HackYourFuture/CommandLine/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/HackYourFuture/CommandLine/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/HackYourFuture/CommandLine/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/HackYourFuture/CommandLine/labels{/name}",
        "releases_url": "https://api.github.com/repos/HackYourFuture/CommandLine/releases{/id}",
        "deployments_url": "https://api.github.com/repos/HackYourFuture/CommandLine/deployments",
        "created_at": "2016-12-04T13:31:41Z",
        "updated_at": "2017-08-30T14:01:08Z",
        "pushed_at": "2017-03-01T16:29:37Z",
        "git_url": "git://github.com/HackYourFuture/CommandLine.git",
        "ssh_url": "git@github.com:HackYourFuture/CommandLine.git",
        "clone_url": "https://github.com/HackYourFuture/CommandLine.git",
        "svn_url": "https://github.com/HackYourFuture/CommandLine",
        "homepage": null,
        "size": 7,
        "stargazers_count": 2,
        "watchers_count": 2,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 5,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 5,
        "open_issues": 0,
        "watchers": 2,
        "default_branch": "master",
        "permissions": {
            "admin": false,
            "push": false,
            "pull": true
        }
    },
]

console.log(repoArray[2].name);

// Repository Titles

let logo = document.createElement('img')

logo.setAttribute('src', repoArray[0].owner.avatar_url);

logo.setAttribute("width", "100px");


// "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4"
document.body.appendChild(logo);





//Creates UL element and appends it to left DIV
let repoUL = document.createElement('ul');

let leftDIV = document.getElementById('left');

leftDIV.appendChild(repoUL);

//Creates LI elements

for (i in repoArray) {
    let repoLI = document.createElement('li');

    repoLI.innerHTML = repoArray[i].name;//Populates LI elements with repository names

    repoLI.setAttribute('id', 'left'+[i]);

    repoUL.appendChild(repoLI); //Appends repoLI to repoUL
}

// Repository Details

//Creates UL element and appends it to right DIV

let deetUL = document.createElement('ul');

let rightDIV = document.getElementById('right');

rightDIV.appendChild(deetUL);

//Creates LI elements

for (i in repoArray) {

    //Stargazers Count
    let starLI = document.createElement('li'); 

    starLI.innerHTML = "Number of stargazers: " + repoArray[i].stargazers_count;//Populates LI elements with stargazer count

    starLI.setAttribute('class', [i]);

    for (let z in repoArray) {
        deetUL.appendChild(starLI); //Appends starLI to deetUL
    }

    //    -------------------------------------------------------------

    //Watchers Count
    let watchLI = document.createElement('li'); 

    watchLI.innerHTML = "Number of watchers: " + repoArray[i].watchers;//Populates LI elements with watchers count

    watchLI.setAttribute('class', [i]);

    for (let z in repoArray) {
        deetUL.appendChild(watchLI); //Appends watchLI to deetUL
    }

    //    -------------------------------------------------------------


    //Forks Count
    let forkLI = document.createElement('li'); 

    forkLI.innerHTML = "Number of forks: " + repoArray[i].forks;//Populates LI elements with forks count

    forkLI.setAttribute('class', [i]);

    for (let z in repoArray) {
        deetUL.appendChild(forkLI); //Appends forkLI to deetUL
    }
    //    -------------------------------------------------------------


    //Language Count
    let langLI = document.createElement('li'); 

    langLI.innerHTML = (repoArray[i].language == null) ? 'Language: -': "Language: " + repoArray[i].language;//Populates LI elements with language


    langLI.setAttribute('class', [i]);

    for (let z in repoArray) {
        deetUL.appendChild(langLI); //Appends forkLI to deetUL
    }
}

